### PR TITLE
Added space from "redirects to " to the url

### PR DESCRIPTION
**Pull request by lfarah**
Soooo, I've been seeing this a lot on AwesomeiOS:

screen shot 2016-11-22 at 11 36 37 pm

### CODE REVIEW

**Comment by dkhamsing** [comment]
thx!
related to this, github has updated their parsing so the links no longer works

however i was told it would be fixed soon

**Comment by dkhamsing** [comment]
@lfarah let me find out if they have a related bug for `<br>` rendering

**Comment by lfarah** [comment]
@dkhamsing It's because of this:
screen shot 2016-11-25 at 11 06 51 pm

**Comment by dkhamsing** [comment]
yup
thx

still waiting on update

**Comment by dkhamsing** [comment]
Looks like issues are fixed
Can u confirm

**Comment by lfarah** [comment]
It is fixed.

**Pull request closed without merging**
