### PR TITLE
Add an option to check github commit age

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by dkhamsing** [comment]
Why is this necessary? What's the use case

**Comment by Moshe-Immerman** [comment]
See the discussion at https://github.com/veggiemonk/awesome-docker/pull/455 - but primarily tagging items as EOL/Abandoned

**Comment by dkhamsing** [comment]
Oh I see
Pretty interesting but I don't think this belongs to this project

Please consider forking and creating a different tool 

Let me know if you need help getting started

**Comment by dkhamsing** [comment]
Check this out http://danger.systems/

**Pull request closed without merging**
