### PR TITLE
Option to completely skip checking white listed URLs

### PR DESCRIPTION
**Pull request by andyortlieb**
I need this feature to prevent downloading very large files that are discoverable in my docs. If this mode is too broad, I could instead make a --skip-list in the same notation as --white-list. Let me know if that would be better.

Thanks

### CODE REVIEW

**Comment by andyortlieb** [comment]
I'm not fully grokking the travisCI output, but if I'm understanding it correctly, I believe the other outstanding PR is failing in the same fashion--so I'm not sure if my code is contributing to this failure.

    The command "awesome_bot bin/assets/test-request-delay -d 1" exited with 1.

**Comment by dkhamsing** [comment]
Travis CI test is broken - should not be because of your changes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Apologies for the delay, I will not be able to review this for a while. Sorry.

**Comment by dkhamsing** [comment]
Sorry could you fix conflicts? 🙏

**Comment by dkhamsing** [comment]
Closing because of lack of activity

**Pull request closed without merging**
