### PR TITLE
Docker instruction + examples added

### PR DESCRIPTION
**Pull request by ruzickap**
Docker instruction + examples added.

Note: Before you test the examples / merge this PR, please create your Automated Docker build:

https://docs.docker.com/docker-hub/builds/

Now you do not have any repositories (images) in your Docker Hub: https://hub.docker.com/r/dkhamsing/

### CODE REVIEW

**Comment by ruzickap** [comment]
Please check+merge #158 first... :-)

**Comment by dkhamsing** [comment]
thank you @ruzickap !

**Comment by ruzickap** [comment]
Actually you didn't do the "Automated Docker build" as I mentioned above.

There are no images in your docker hub repository https://hub.docker.com/r/dkhamsing/

Without it - the steps are useless...

**Comment by dkhamsing** [comment]
Oops my bad 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ruzickap** [comment]
Ok...

But you need to create the "Automated Docker build" anyway...

Please follow the steps here: https://docs.docker.com/docker-hub/builds/ and create the "automated build" in your repository: https://hub.docker.com/r/dkhamsing/

I can not do it for you, because only the owner of this repository can do it...

Thank you.

**Comment by dkhamsing** [comment]
Thx! Will have to do this later. Sorry not familiar at all 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
