### PR TITLE
Add --ignore-ssl option to skip ssl verify 

### LINKED ISSUE #44: Add a --ignore-ssl-certificate option
I was creating a travis.yml for awesome-github and ran across a link that didn't match the server cert - `https://www.gitbook.io/book/gitbookio/markdown hostname "www.gitbook.io" does not match the server certificate`

It would be great to be able to disable that check like we can disable checking for dupes.

### PR DESCRIPTION
**Pull request by vkarampinis**
#44

### CODE REVIEW

**Comment by dkhamsing** [comment]
Wow! Thanks will review asap

**Comment by vkarampinis** [comment]
Waiting for your review/merge, so I can remove those invalid ssl sites from my whitelist :)

**Comment by dkhamsing** [comment]
:wink:

**Comment by dkhamsing** [comment]
@vkarampinis do you have any sites I can test this with?

I tried with these but they still give me issues

```
  1. https://kismatic.com/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
  2. https://kismatic.com/community/introducing-kubernetes-weekly-news/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
  3. https://this-week-in-rust.org/ Connection reset by peer - SSL_connect
  4. https://data.nasdaq.com/ SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```

**Comment by vkarampinis** [comment]
My tests was with: https://pictonic.co

**Comment by vkarampinis** [comment]
```
$ awesome_bot test-ssl --ignore-ssl
> Checking links in test-ssl
> Will ignore SSL certificate validation
Links found: 5
  1. https://pictonic.co
  2. https://kismatic.com/
  3. https://kismatic.com/community/introducing-kubernetes-weekly-news/
  4. https://this-week-in-rust.org/
  5. https://data.nasdaq.com/
Checking URLs: ✓?✓✓✓

Issues :-(
> Links
  1. https://data.nasdaq.com/ SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
> Dupes
  None ✓
```

**Comment by dkhamsing** [comment]
Hm weird, I don't get the same results.. hey do you know how we can suppress the `nasdaq` error too ?

**Comment by dkhamsing** [comment]
Not consistent.. :confused: 

```
$ awesome_bot test-ssl --ignore-ssl
> Checking links in test-ssl
> Will ignore SSL certificate validation
Links found: 5
  1. https://pictonic.co
  2. https://kismatic.com/
  3. https://kismatic.com/community/introducing-kubernetes-weekly-news/
  4. https://this-week-in-rust.org/
  5. https://data.nasdaq.com/
Checking URLs: ????✓

Issues :-(
> Links 
  1. https://kismatic.com/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
  2. https://kismatic.com/community/introducing-kubernetes-weekly-news/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
  3. https://data.nasdaq.com/ SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
  4. https://this-week-in-rust.org/ Connection reset by peer - SSL_connect
> Dupes 
  None ✓

```

**Comment by dkhamsing** [comment]
Also without ignore

```
$ awesome_bot test-ssl 
> Checking links in test-ssl
Links found: 5
  1. https://pictonic.co
  2. https://kismatic.com/
  3. https://kismatic.com/community/introducing-kubernetes-weekly-news/
  4. https://this-week-in-rust.org/
  5. https://data.nasdaq.com/
Checking URLs: ????✓

Issues :-(
> Links 
  1. https://data.nasdaq.com/ SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
  2. https://this-week-in-rust.org/ Connection reset by peer - SSL_connect
  3. https://kismatic.com/community/introducing-kubernetes-weekly-news/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
  4. https://kismatic.com/ SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure
```

**Comment by dkhamsing** [comment]
Will do more testing tomorrow with Travis

**Comment by vkarampinis** [comment]
I have no experience with ruby, but with some research I made yesterday, it seems to be something buggy in `faraday` lib or internaly with `http`

I opened an issue there lostisland/faraday#558

**Comment by dkhamsing** [comment]
@vkarampinis thanks

**Comment by RichardLitt** [comment]
Another possible site to test: http://calltospeakers.com/

**Comment by dkhamsing** [comment]
ok

**Comment by dkhamsing** [comment]
Sorry it's been a while, gonna make a test branch and do some testing

**Comment by dkhamsing** [comment]
Check out: https://github.com/dkhamsing/travisci-playground/tree/awesome_bot/ssl
Results: https://travis-ci.org/dkhamsing/travisci-playground/builds/110540272

Looks like the option will fix this particular error `certificate verify failed` but there are other ssl errors.

```
  1. https://this-week-in-rust.org/ Connection reset by peer - SSL_connect
  2. https://data.nasdaq.com/ SSL_connect SYSCALL returned=5 errno=0 state=unknown state
  3. https://kismatic.com/community/introducing-kubernetes-weekly-news/ SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure
  4. https://kismatic.com/ SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure
```

Maybe the option should be renamed `--ignore-ssl-verify`? Not sure if it's worth it

**Comment by dkhamsing** [comment]
@vkarampinis @RichardLitt any thoughts?

**Comment by RichardLitt** [comment]
If there's nothing I as a maintainer of a list can do to fix the SSL cert, and the address still works in the browser, then I should be able to ignore it. Make sense?

**Comment by dkhamsing** [comment]
@RichardLitt sure makes sense

**Comment by dkhamsing** [comment]
@vkarampinis I'm thinking implementing this to ignore all ssl errors involves going beyond ssl verify and 
 looking at the error .. Is that something you want to take on ?

**Comment by dkhamsing** [comment]
Closing for now since there is no activity.. #44 still stand

**Pull request closed without merging**
