### PR TITLE
Switch to Github Actions

### PR DESCRIPTION
**Pull request by ozh**
PR to drop Travis and use Github Actions instead - resubmitted differently in hope the workflow action will run this time 🤞

### CODE REVIEW

**Comment by ozh** [comment]
Sorry, dunno why the action isn't running in this PR

Results once merged in : https://github.com/ozh/awesome_bot_temp/actions/runs/818067700 - same as Travis, except much, much, much faster 😄

**Comment by dkhamsing** [comment]
@ozh thx for all this work! will have to take a look later 🙏

**Comment by ozh** [comment]
@dkhamsing please let me know if I can help with this PR

**Comment by ozh** [comment]
Any news? 😅

**Review by Inncee81 — APPROVED** [review]

**Review by Inncee81 — APPROVED** [review]

**Comment by dkhamsing** [comment]
@ozh sorry haven't had a chance to check this out, thank you so much for your contribution 🙏

**Comment by dkhamsing** [comment]
@ozh closing this, can you create a new pull request. I think GitHub has changed its process to allow these actions to be run on an approval basis 

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by ozh** [comment]
@dkhamsing I've submitted this PR way after the changes mentioned in the article you link.

From what I understand, it's up to you to allow the action to run, as described in [the second link](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) you share above: [Approving workflow runs on a pull request from a public fork](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork)

**Comment by dkhamsing** [comment]
@ozh these are the options visible to me.. not seeing the new option to run the action

Screen Shot 2021-07-30 at 1 16 02 PM

**Comment by dkhamsing** [comment]
The blog post is from August, the PR is from May.. not sure if important

**Comment by dkhamsing** [comment]
Might be bonked, anyway, testing myself using a branch, thank you https://github.com/dkhamsing/awesome_bot/actions/runs/1083481362

**Comment by dkhamsing** [comment]
Thx @ozh

**Pull request merged**
