### PR TITLE
Delay: Integer -> Float

### PR DESCRIPTION
**Pull request by agsdot**
Shared some thoughts on https://github.com/dkhamsing/awesome_bot/commit/811ddf2cea614d30d9a3e80a62e7b33845d89176#r45867564

### CODE REVIEW

**Comment by agsdot** [comment]
Sidenote: I noticed on Github Actions vs Travis, I get the 429 error a lot more frequently. Is there a reason you suspect this is happening @dkhamsing ?

**Comment by dkhamsing** [comment]
Thx for the pull request @agsdot. How can I test this small change?

Not sure about the 429 errors.. sorry 😓

**Comment by agsdot** [comment]
Hi @dkhamsing , I'm not sure about how to test it. My ruby-fu / gemspec-fu is not that super polished. I figured you had a good way to test edge cases on changing an Integer to a Float.

Ah, ok. Just wanted to make you aware of the 429 areas no Github Actions. If you encounter it elsewhere or you find a solution, thanks for sharing.

**Comment by dkhamsing** [comment]
@agsdot sorry it took so long. Thx for this, looks good!

**Pull request merged**
