### PR TITLE
Update status.md

### PR DESCRIPTION
**Pull request by Swati4star**

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thanks for this pull request!

**Comment by dkhamsing** [comment]
Could you also update https://github.com/dkhamsing/awesome_bot/blob/master/status/list-travis-ci

**Comment by Swati4star** [comment]
@dkhamsing Updated.

Just a suggestion, currently the repo names in the list(s) are in random order. Shouldn't these be in alphabetical order?

**Comment by dkhamsing** [comment]
It’s meant to be sorted by popularity but that’s a little more involved 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
