### PR TITLE
Add emacs-tw/awesome-emacs to list-travis-ci

### PR DESCRIPTION
**Pull request by agsdot**

### CODE REVIEW

**Comment by agsdot** [comment]
@dkhamsing, can you update the awesome_bot image(s) hosted on https://hub.docker.com/r/dkhamsing/awesome_bot/ ? The image appears to be several years old, and only has the "latest" version but no tagged versions corresponding to the tagged versions of the awesome_bot github repo. If there can be a "latest" image as well as several tagged versions, that would be great.

On [emacs-tw/awesome-emacs](https://github.com/emacs-tw/awesome-emacs), I've been using the awesome_bot binary available the gem install for the past couple years. Recently, I updated the travis file (https://github.com/emacs-tw/awesome-emacs/blob/master/.travis.yml) to source emacs via a docker image. I decided to do the same with the awesome_bot binary (reduce the need for a ruby image and the gem install requirement). I'd like to ensure that the awesome_bot binary sourced via docker is the most up to date version.

**Comment by dkhamsing** [comment]
hi @agsdot I'm not super familiar with docker (don't use that myself).

Could you leave some steps here for what needs to be changed for docker? thank you

cc @ruzickap

**Comment by dkhamsing** [comment]
Thx for updating `status.md`!

**Comment by agsdot** [comment]
Great question @dkhamsing , I'm actually only starting to use docker more myself. I don't think I've created a docker hub account in the past much less published images to it. @ruzickap , thanks for any help in updating awesome_bot on docker hub.

Sidenote, I was looking for other examples of .travis.yml setups using awesome_bot via docker and mostly/only found gem install setups. It was nice to experiment with the docker image -- a year or so ago, one person commented on the awesome-emacs repo and asked why ruby was there (I cited the awesome_bot gem), also I wonder if CI processes faster or not. It's nice to experiment with something new.

**Comment by agsdot** [comment]
@dkhamsing re: updating the status.md, no problem. First time I did the patch-1 edit on the web gui, and noticed travis didn't pass. Cloned it locally and ran the ruby script to fix things up and update the status.md file.

Sidenote, I really enjoyed perusing and reading through the status.md file. I wonder and am guessing that there are some repos there that may not be on awesome.re / https://github.com/sindresorhus/awesome#readme .

**Comment by dkhamsing** [comment]
Yeah definitely possible 🤔 

In the topic of new ways of using `awesome_bot`, I tried using it with GitHub actions / workflows here https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/workflows/ruby.yml 👀

**Comment by agsdot** [comment]
Nice! Thanks for sharing. Haven't delved into circle or github actions yet for CI, but it's always good to have more examples.

**Comment by dkhamsing** [comment]
GitHub actions seem very fast ⚡️

**Comment by agsdot** [comment]
Thanks for the insights about Github Actions. Experimented with it a little last week, couldn't quite get the docker image to work properly on it.

@ruzickap can you provide some insights/help in updating the Docker awesome bot image (https://hub.docker.com/r/dkhamsing/awesome_bot/tags) to be a tagged version of 

  - latest
  - 1.19.1
  - 1.19.0
  - 1.18.0

Right now, as it stands "latest" was "last updated 3 years ago." And there is only one image "latest"

The dockerfile is for the regular ruby image and not the ruby:alpine image. I'm guessing/hoping that with the ruby:alpine image the dockerfile image pulls and runs faster.

Thanks!

**Comment by ruzickap** [comment]
Go to Docker Hub (https://hub.docker.com/r/dkhamsing/awesome_bot) and go to "Builds" tab.

On that page you should see "Automated Builds" and you should configure it like:

image

Currently I can see that there is "No autobuilds available" message :-(

**Comment by agsdot** [comment]
This is what I see too:

Screen Shot 2020-09-19 at 12 12 16 PM

Is that something the docker hub project owner (i.e. @dkhamsing ) needs to do on their end? To initiate the build?

**Comment by dkhamsing** [comment]
Let me try, thx

**Comment by agsdot** [comment]
:D 👍

**Comment by dkhamsing** [comment]
Uh added a couple of builds but not sure if they work (especially the 2nd one) https://hub.docker.com/repository/docker/dkhamsing/awesome_bot/builds
Let me know if anything needs to be changed

Thank you!

**Comment by dkhamsing** [comment]
Are you saying the change I made for docker made it worse??

As far as 429, it means `429 Too Many Requests` so it should be discarded, using option `--allow 429`: try this 

`$AWESOME_BOT README.org --allow 429 --allow-ssl --white-list $allowed_internal_links,$allowed_redirect_links`

**Comment by agsdot** [comment]
@dkhamsing sorry about littering the thread. Just put the whole console output here in this closed PR. Not sure if you mind that or this should be another issue opened about updating the docker images.

**Comment by agsdot** [comment]
I don't know if it made it worse or not. I noticed the issue on github actions with the old docker image.

What would cause the "429 Too Many Requests".

The below console output is being run on my local macbook. The emacswiki 443, I would disregard, but it's the other "x" instances that bother me.


```console
  595. https://licensebuttons.net/p/zero/1.0/88x31.png
  596. https://github.com/emacs-tw
Checking URLs: ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓xx✓✓✓✓✓xxxxx✓xxxx✓xxx✓✓xxx✓xxx✓xxxxxxx✓x✓xxxx✓✓xxx✓xxxxxx✓xxxx✓xx✓x✓✓xxxxx✓xxxxx✓xxx✓✓xx✓xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx✓xxx✓x✓✓xx✓xx✓xxxxxxxxxxx✓xxxxxxx✓xxxxxx✓✓xxxxxxx✓x✓xxxx✓xxx✓xxxxxxxxxxx✓xxx✓xxx?x??xx✓xxx✓xxxxxxxx✓xxx✓✓xx✓xxxxxxxxx✓xxxxxxx✓xxxxx✓✓xxx?xxx✓x✓x✓✓✓xx✓✓✓✓?✓xxxxx✓xxxxx✓xxx?xxxxxxxxxxxxxxxxxxxx?✓✓xxxxxxxxx✓xxxxxxxx?xxxxxxxxxxxxxxxxxxxxx✓xxx✓xx✓?✓xxxx✓xxxx✓xx✓✓xx✓xxxx✓xx?xxxxx✓xxxxx✓x✓xxxxxxx?✓✓xxx✓✓x✓✓✓✓✓✓✓✓✓✓✓x✓x✓?✓?
Checking white listed URLs: ??xx→✓

> White listed:
  1. [L0008] 429 https://github.com/melpa/melpa
  2. [L0440]  http://ternjs.net/doc/manual.html#emacs] bad URI(is not URI?): "http://ternjs.net/doc/manual.html#emacs]"
  3. [L0906] 429 https://github.com/freesteph/peach-melpa.org
  4. [L0906] 200 https://peach-melpa.org/
  5. [L1017]  https://melpa.org/#/toc-org] bad URI(is not URI?): "https://melpa.org/#/toc-org]"
  6. [L1032] 302 https://awesome.re  → https://github.com/sindresorhus/awesome#readme

Issues :-(
> Links
  01. [L0150]  https://www.emacswiki.org/ Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  02. [L0676]  https://www.emacswiki.org/emacs/CategoryEshell Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  03. [L0677]  https://www.emacswiki.org/emacs/AnsiTerm Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  04. [L0678]  https://www.emacswiki.org/emacs/MultiTerm Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  05. [L0761]  https://www.emacswiki.org/emacs/LaTeXPreviewPane Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  06. [L0777]  https://www.emacswiki.org/emacs/CategoryGnus Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  07. [L0778]  https://www.emacswiki.org/emacs/MessageMode Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  08. [L0783]  https://www.emacswiki.org/emacs/WanderLust Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  09. [L0788]  https://www.emacswiki.org/emacs/ERC Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  10. [L0790]  https://www.emacswiki.org/emacs/rcirc Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  11. [L0825]  https://www.emacswiki.org/emacs/ELPA Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  12. [L0911]  https://www.emacswiki.org/emacs/Mpc Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
  13. [L0925]  https://www.emacswiki.org/emacs/ZoneMode Failed to open TCP connection to www.emacswiki.org:443 (Connection refused - connect(2) for "www.emacswiki.org" port 443)
> Dupes
  None ✓

```

**Comment by agsdot** [comment]
Here was my separate downstream forked repo test of github actions: https://github.com/agsdot/awesome-emacs/runs/1113358957 with the old docker image

I noticed similar to this updated docker image, the first 100 or so checks, well "check" out for the links, then the X failures start popping up frequently

Screen Shot 2020-09-19 at 12 53 48 PM

**Comment by dkhamsing** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
> The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").

I wonder if this option would help `-d, --request-delay [seconds]    Set request delay`:
`$AWESOME_BOT README.org -d 1 --allow-ssl --white-list $allowed_internal_links,$allowed_redirect_links`

Not sure if that would become too slow for you. Maybe not important if it's automated?

**Comment by agsdot** [comment]
Hum... not really a fun of using a delay. Also can the interval be say, 0.1 or 0.5 seconds not just integer second values? I went with docker to pull the emacs and awesome_bot image to simplify things and hopefully create the CI build faster and more reliably. Don't really want to slow things down.

On a lighter note, https://travis-ci.org/github/agsdot/awesome-emacs/builds/728633960, my travis build for the forked branch built successfully!

```yaml
  - docker pull dkhamsing/awesome_bot:latest
  - docker pull silex/emacs:27.1-alpine
  - export AWESOME_BOT="docker run -ti --rm -v $(pwd):$(pwd) -w $(pwd) dkhamsing/awesome_bot:latest"
```

I added in the awesome_bot:latest tag and it built fine. Odd though that on my local computer (macbook and some random ISP) and on github actions I get the 4XX errors. I wonder why that is? Do Travis servers have a better network connection such that timeouts don't occur?

So status quo with regards to the docker image build as to causing issues on travis. Funny though, the previous docker build did not have timeouts on my local computer. 

I guess this is / would be a last request (nice to have).

Is it possible to create one or two docker builds such that it can be pulled such as 

docker pull dkhamsing/awesome_bot:latest
docker pull dkhamsing/awesome_bot:1.19.1
docker pull dkhamsing/awesome_bot:1.19.0

Similar to how for the docker
docker pull silex/emacs:27.1-alpine
docker pull silex/emacs:26.3-alpine
docker pull silex/emacs:26.2-alpine

**Comment by agsdot** [comment]
@dkhamsing and @ruzickap greatly improved docker build time with the :latest image.

Screen Shot 2020-09-19 at 1 19 41 PM

Screen Shot 2020-09-19 at 1 18 39 PM

From ~20 seconds to ~3 seconds. It is now (logically) building faster the emacs alpine image! Your help was greatly appreciated! Thanks!

**Comment by dkhamsing** [comment]
wow a big change

Looks like `latest` is working, let me see if I can get the other working

**Comment by dkhamsing** [comment]
@agsdot hmm updated settings, can u try `docker pull dkhamsing/awesome_bot:1.19.1` ?

**Comment by agsdot** [comment]
re: "wow a big change"

Yeah, I know; it's great! Really appreciated. Went to using both alpine images instead of ubuntu based images for both emacs and awesome_bot and the images pull a lot faster. It's really nice. Thanks once again @dkhamsing.

Did you produced a tagged build of 1.19.1? I still only see latest on the website. Tried to run "docker pull dkhamsing/awesome_bot:1.19.1" and it errored out.

Screen Shot 2020-09-19 at 2 41 43 PM

Screen Shot 2020-09-19 at 2 41 50 PM

Screen Shot 2020-09-19 at 2 41 53 PM

It looks like your builds are still called "latest" .

**Comment by dkhamsing** [comment]
Hm I think the tag builds (`docker pull dkhamsing/awesome_bot:x.x.x`) will only be for future pushes.. did you need a specific older one, I could manually build that for you

**Comment by agsdot** [comment]
Having two versions, latest and 1.19.1, should be good. It would be good to anchor the CI travis script at a particular version of awesome_bot rather than a floating/rolling latest even if it does or doesn't rarely changes.

Screen Shot 2020-09-19 at 2 49 59 PM

Going forward, if the tagged versions on the git log can be produced into docker hub images that would be great. Much appreciated once again. 

@dkhamsing thanks for producing the awesome_bot binary. It prevents a lot of link rot for the awesome bot projects and helps with maintenance. Much appreciated. Thanks!

**Comment by dkhamsing** [comment]
Glad to be able to help!

@agsdot can you try this one off (manual build of 1.19.1, but with a different name to trigger on docker hub): `docker pull dkhamsing/awesome_bot:1.9.1-docker`

**Comment by agsdot** [comment]
Screen Shot 2020-09-19 at 3 11 52 PM

Screen Shot 2020-09-19 at 3 12 03 PM

Builds and works clean. Really enjoying the 2.89 second build times. Thanks for updating the images to "latest" and "1.19.1-docker" and changing from the ubuntu to alpine base. It's a lot more crisp and clean.

**Pull request merged**
