### PR TITLE
Add awesome falsehood

### PR DESCRIPTION
**Pull request by kdeldycke**
Just added auto-check of links on my awesome list following https://github.com/kdeldycke/awesome-falsehood/issues/14.

As a bonus, I also removed all trailing spaces featured in the source.

### CODE REVIEW

**Comment by dkhamsing** [comment]
@kdeldycke thanks for your contribution
can you also update 
https://github.com/dkhamsing/awesome_bot/blob/master/status/list-travis-ci

**Comment by kdeldycke** [comment]
@dkhamsing : sure! Just did that in ffc78ad9727088489a8eb5855690ddfac96de6e3.

This PR is ready to be merged.

**Comment by dkhamsing** [comment]
Thx

**Comment by kdeldycke** [comment]
Thanks for the quick merge! :)

**Pull request merged**
