### PR TITLE
Relative files on disk

### PR DESCRIPTION
**Pull request by andyortlieb**
This change allows the user to check links available on disk, rather than needing to run a web server for you uncommitted project. This will be helpful for people who write docs that reference themselves.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Apologies for the delay, I will not be able to review this for a while. Sorry.

**Comment by dkhamsing** [comment]
@andyortlieb this is listed as an usage example in the readme - would that work for what you want to do?

```
$ awesome_bot docs/*.md
# check all markdown files in docs/ directory
```

**Comment by andyortlieb** [comment]
> @andyortlieb this is listed as an usage example in the readme - would that work for what you want to do?
> 
> ```
> $ awesome_bot docs/*.md
> # check all markdown files in docs/ directory
> ```

@dkhamsing The --base-url flag allows it to assume a base url for the destination check, not the source file to be checked. I know this isn't the original intent of awesome bot, however it was an easy change that allows me to validate references contained within a single project, or another local project on disk.

**Comment by dkhamsing** [comment]
@andyortlieb please give me an example, I am still not following what you want to do and the difference with the example I provided. Thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andyortlieb** [comment]
It's in my update in the readme. Basically, I want to test the integrity of
my own markdown docs that refer to other parts of themselves, instead of on
some other deployed website. So the file that i am testing is not the
interesting subject here, but the location it refers to is.

**Comment by dkhamsing** [comment]
Thanks for the explanation - it is a bit better but still confusing. In particular, your update to the README. 

In the end, you are correct - this does not seem as useful - thank you for the contribution - will pass for now. Hope you can use your own modifications for yourself 🙏

**Pull request closed without merging**
