### PR TITLE
Enable support for partial seconds

### LINKED ISSUE #145: --request-delay only accepts integers
You cannot `--request-delay` with floating point numbers. So you cannot use partial seconds.

### PR DESCRIPTION
**Pull request by baynezy**
Allows floating point numbers for --request-delay

Closes #145

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hm what kind of testing did you do?

**Comment by baynezy** [comment]
I added a new line to the Travis configuration exercising this change.

See line `25` of `.travis.yml`

**Comment by dkhamsing** [comment]
I saw that but how did you test the actual amount of time being delayed

**Comment by baynezy** [comment]
I've done nothing more than that. I just follow the precedent set in #123 I can add more testing.

**Comment by dkhamsing** [comment]
Yeah it would be great to test the delay duration.. you could do it manually and time the whole run. Does that make sense

**Comment by dkhamsing** [comment]
You know what, not sure this is really necessary

Thanks for the effort :)

**Comment by baynezy** [comment]
@dkhamsing do you mean the extra testing isn't necessary or the feature

**Comment by dkhamsing** [comment]
Feature

**Comment by baynezy** [comment]
That is a shame as I could really use this in my use case. I'll have to use my fork

**Comment by dkhamsing** [comment]
Sorry and thanks for the effort - will be open to this again if there is more interest 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
